### ISSUE TITLE
dockerForm task doesn't use relative paths 

### ISSUE THREAD

**Issue by davidawad** [corda/corda-gradle-plugins#399]
This is perhaps more of a feature request, but right now when the dockerform task generates a docker-compose file it uses the full path, which means that this docker-compose configuration isn't portable to another machine. 

```
version: '3'
services:
  notary:
    volumes:
    - /Users/davidawad/Desktop/samples-java/Features/customlogging-yocordapp/build/nodes/Notary/node.conf:/etc/corda/node.conf
    - /Users/davidawad/Desktop/samples-java/Features/customlogging-yocordapp/build/nodes/Notary/certificates:/opt/corda/certificates
    - /Users/davidawad/Desktop/samples-java/Features/customlogging-yocordapp/build/nodes/Notary/logs:/opt/corda/logs
```

It would be quite nice if there was an option to just have it output the relative paths in order for the configuration to be portable to another machine if someone wanted to do that. 

```
version: '3'
services:
  notary:
    volumes:
    - ./Notary/node.conf:/etc/corda/node.conf
    - ./Notary/certificates:/opt/corda/certificates
    - ./Notary/logs:/opt/corda/logs
```
